import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from './components/Navigation/Navigation'
import styles from './page.module.css'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { AuthProvider } from './provider/AuthProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Todo-list',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={styles.html}>
			<body
				className={inter.className}
				style={{
					margin: 0,
					padding: 0
				}}>
				<AuthProvider>
					<Navigation />
					{children}
					<ToastContainer />
				</AuthProvider>
			</body>
		</html>
	)
}
